### ISSUE TITLE
Newsweek

### ISSUE THREAD

**Issue by abongsjoel** [danielufeli/newsweek-replica#2]
This issue is created for the peer-to-peer code review of team-161

**Comment by abongsjoel** [comment]
Great work so far

**Comment by abongsjoel** [comment]
When making use of HTML5 semantic elements, after the 
```
<header>...</header> 
```
section, you could create a 
```
<main>...</main>
``` 
section to hold the main parts of your page and a 
```
<footer>...</footer> 
```
section for the footer.

**Comment by danielufeli** [comment]
ok thanks, I have added it.
